const fruits = [
    {
        
        "name": "Apple",
        "genus": "Malus",
        "type": "Fruit",
        "light": "Sun",
        "description": "Apple is the most widely adapted of all temperate-zone fruit trees. A copious producer if it's planted in full sun and well-drained soil, a mature tree will supply several families with bushels of fruit. Many cultivars have chilling requirements that must be met for fruits to develop properly. Choose a cultivar that will thrive in your climate. Also, plant two or more cultivars that bloom at the same time to ensure cross-pollination and a variety of fruits, or choose a self-pollinating cultivar if you have room for just one tree.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2015%2F06%2F16002958%2F100142389.jpg&q=85",
        "propagation": "Grafting",
        "height": "3 to 8 feet",
        "width": "2-40 feet wide",
        "flower_color": "White",
        "foliage_color": "None",
        "problem_solvers": "None",
        "special_features": "Good for Containers",
        "care_must_knows": "Expect to wait 3-5 years after planting for your first full harvest. Fruits ripen 70-180 days from bloom, depending on the cultivar. Pick apples by hand to avoid bruising them. A ripe apple separates easily from the branch and has firm flesh. A soft apple is overripe but can still be used for cooking. Late-season varieties are the best for long-term storage at cool room temperatures. Some types, such as Cox, McIntosh, and Jonathan, decay if stored in the refrigerator."
      },
      {
        
        "name": "Blackberry",
        "genus": "Rubus spp.",
        "type": "Fruit",
        "light": "Part Sun",
        "description": "Blackberries are delicious, nutrient-rich, and relatively easy to grow—making them perfect additions to your home garden or landscape. Even though they bear thorns, the canes are attractive with lush green foliage, white blushing, and charming white flowers.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2016%2F02%2F31231142%2FBKS018981.jpg&q=85",
        "propagation": "Division",
        "height": "3 to 8 feet",
        "width": "3 to 10 feet",
        "flower_color": "White",
        "foliage_color": "Blue/Green",
        "problem_solvers": "None",
        "special_features": "Attracts Birds",
        "care_must_knows": "Juicy, deep blue-black berries appear on thornless, semi-erect canes. It's quite vigorous. Plant blackberry in a spot that has full sun (at least 6 to 8 hours of direct sun per day) to keep your plants healthy and productive. While blackberry will grow in partial or full shade, it will be more susceptible to disease and produce fewer and lower quality fruits than when it's grown in the sun.\nBlackberry isn't particularly fussy about soil type. But like most fruits and vegetables, it does best in moist, well-drained soil that's rich in organic matter. If your ground has a high clay content, amend liberally with organic matter at planting time to help give your blackberry the best possible start.\nPrune blackberry in two waves to keep it productive. The first wave, which happens in spring, is called tip pruning because you simply cut off the top couple of inches of new growth. This encourages your blackberry plants to produce more side branches—which means more fruit. The second wave of pruning happens in late summer. Remove any stems that produced fruit; those stems won't produce fruit the following year. Removing these spent stems will keep your blackberry patch from getting overgrown and can help reduce incidence of disease."
      },
      {
       
        "name": "Blueberry",
        "genus": "Vaccinium",
        "type": "Fruit",
        "light": "Sun",
        "description": "Tasty blue fruits and vibrant fall foliage make blueberry plants landscape all-stars. Call on this plant to create a multitasking hedge. Add several blueberries to a shrub border as a colorful, fruitful planting partner. Plant breeders have selected many new varieties that thrive in containers, producing patio-side fruit that is just as sweet and delectable as the fruit grown on 8-foot-tall shrubs.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2016%2F02%2F31230342%2F100215400.jpg&q=85",
        "propagation": "Stem Cuttings",
        "height": "1 to 3 feet",
        "width": "2 to 10 feet",
        "flower_color": "White",
        "foliage_color": "Blue/Green",
        "problem_solvers": "None",
        "special_features": "Attracts Birds",
        "care_must_knows": "Plant container-grown blueberry plants in spring or early summer. Be sure to water them deeply once a week during the first growing season. Early spring is the best time to plant the dormant, bare-root blueberry plants from mail-order sources. Soak the roots of bare-root plants in water for about an hour before planting."
      },
      {
       
        "name": "Cherry",
        "genus": "Prunus spp.",
        "type": "Fruit",
        "light": "Sun",
        "description": "A plump, juicy cherry is a luxurious treat—for humans and wildlife alike. Whether you grow sweet or sour cherries, plan to share. This is usually not a problem—a mature tree produces more fruit than a typical family can consume. When choosing a cherry variety, select one that is disease-resistant, grows to the right size for your space, and is adapted to your local conditions. The smaller the tree, the easier it will be to harvest the fruit.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2016%2F02%2F31230048%2F100851145.jpg&q=85",
        "propagation": "Grafting",
        "height": "8 to 20 feet",
        "width": "10 to 30 feet",
        "flower_color": "White",
        "foliage_color": "Blue/Green",
        "problem_solvers": "None",
        "special_features": "Attracts Birds",
        "care_must_knows": "Prune your cherry trees to keep them small (which makes them easier to harvest) and encourage productivity. The best time to prune cherry trees is in winter while they are dormant and leafless. Start by removing any offshoots (called suckers) that develop at the base of the tree. Get rid of any dead or diseased growth and branches that grow in proximity and rub together."
      },
      {
        
        "name": "Fig",
        "genus": "Ficus carica",
        "type": "Fruit",
        "light": "Sun",
        "description": "Figs often fetch high prices at the grocery store or farmer’s market, but it’s easier than you may think to grow your own—if you live in the right climate and have room for one or more of these shrubs. A large fig can produce plenty of fruit, giving you enough to enjoy along with leftovers to share with friends and neighbors.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2016%2F02%2F31230842%2F101086005.jpg&q=85",
        "propagation": "Leaf Cuttings",
        "height": "8 to 20 feet",
        "width": "10-20 feet",
        "flower_color": "Green",
        "foliage_color": "Blue/Green",
        "problem_solvers": "None",
        "special_features": "Low Maintenance",
        "care_must_knows": "Be sure you select an extra-hardy fig variety. You want to protect your figs from below-average temperatures by wrapping them in burlap and filling the burlap with leaves or pine needles. Alternatively, you can grow figs in large containers, moving them to a protected spot like a garage or shed over winter. If you wish to prune your fig to keep it at a smaller size, the best time is in winter when the plant is dormant and leafless. To keep your fig most productive, remove any offshoots, called suckers, that develop at the base of the plant, as well as any dead or diseased growth. Pruning the main branches back by about a quarter in winter helps ensure you get higher-quality fruit the next year."
      },
      {
        "name": "Fuchsia Flowering Gooseberry",
        "genus": "Ribes speciosum",
        "type": "Fruit",
        "light": "Part Sun",
        "description": "Both you and the hummingbirds will love this easy-to-grow shrub -- as long as you don't have to get too close to it. Sharp spines line the stems and fruits of fuchsia flowering gooseberry. Plant it in a mixed border, away from a walkway or entry. Or tuck it in the back of a border where you can enjoy its flowers and fruit from a distance. The brilliant red fruits dangle like jewels from the stems for weeks. Its red, fuchsia like flowers bloom January through May in temperate climates and attract hummingbirds.Fuchsia flowering gooseberry grows best in part shade or shade. It does not tolerate reflected heat well and grows best in a planting area that receives morning sun and afternoon shade. It will grow in a variety of soils and will remain evergreen when watered regularly during the summer.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2016%2F02%2F31223304%2F101736485.jpg&q=85",
        "propagation": "Stem Cuttings",
        "height": "3 to 8 feet",
        "width": "To 6 feet wide",
        "flower_color": "Red",
        "foliage_color": "None",
        "problem_solvers": "Deer Resistant",
        "special_features": "Low Maintenance",
        "care_must_knows": "Fuchsia flowering gooseberry grows best in part shade or shade. It does not tolerate reflected heat well and grows best in a planting area that receives morning sun and afternoon shade. It will grow in a variety of soils and will remain evergreen when watered regularly during the summer."
      },
      {
       
        "name": "Grape",
        "genus": "Vitis spp.",
        "type": "Fruit",
        "light": "Sun",
        "description": "One of the oldest cultivated crops, grapes have been grown for its fruit that we eat fresh or dried or process into jam, jelly, juice, or wine. Choose varieties that are hardy and well-suited to your area. The long-lived vines require annual maintenance and a few years to come into full production, but the investment of time and care produces results that surpass any supermarket offering.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2016%2F02%2F31230706%2FSIP901592.jpg&q=85",
        "propagation": "Grafting",
        "height": "3 to 8 feet",
        "width": "6-12 feet",
        "flower_color": "None",
        "foliage_color": "None",
        "problem_solvers": "None",
        "special_features": "Attracts Birds",
        "care_must_knows": "Herbicide drift is another consideration, especially in rural areas. Broadleaf herbicides, such as 2,4-D and dicamba, injure grape vines. Choose a site protected from herbicide drift by large trees and inform your neighbors of your grape planting. In urban areas, encourage neighbors to apply broadleaf herbicides in the fall when the herbicide is most effective and does the least damage to grape vines."
      },
      {
       
        "name": "Lemon",
        "genus": "Citrus limon",
        "type": "Fruit",
        "light": "Sun",
        "description": "Productive, fragrant, and beautiful, lemon trees thrive in regions that have a climate similar to the Mediterranean—warm, dry summers with cool winters and little humidity. One lemon tree can produce bushels of fruit. Do you live in a cold climate? Enjoy the beauty and occasional fruit set of a lemon tree by growing one in a pot. Place the potted lemon tree outside in late May to encourage fertilization; bring it back indoors to a bright, sunny location in winter.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2015%2F06%2F16005302%2F100957976.jpg&q=85",
        "propagation": "Grafting",
        "height": "8 to 20 feet",
        "width": "10-15 feet wide",
        "flower_color": "White",
        "foliage_color": "Blue/Green",
        "problem_solvers": "None",
        "special_features": "Low Maintenance",
        "care_must_knows": "Protect a lemon tree from injury by maintaining a grass-free area 2 to 5 feet around the trunk. Spread a 2-inch-thick layer of mulch around the tree to help retain soil moisture and reduce weed competition. A lemon tree requires minimal pruning. Snip away water sprouts (vigorously growing shoots) and dead wood, then shape the tree as desired."
      },
      {
        
        "name": "Lime",
        "genus": "Citrus aurantiifolia",
        "type": "Fruit",
        "light": "Sun",
        "description": "Famous for adding a tropical taste to pies, margaritas, and other tasty foods, limes produce flavor-packed green fruits on a small, thorny, evergreen tree. The flowers are lightly fragrant compared to other citrus, but still add ambiance to the landscape in spring when the trees bloom. Limes grows best in a sunny spot with sandy or well-drained soil with a regular supply of moisture.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2015%2F06%2F15214740%2F100167436.jpg&q=85",
        "propagation": "Seed",
        "height": "Under 6 inches",
        "width": "To 15 feet wide",
        "flower_color": "White",
        "foliage_color": "None",
        "problem_solvers": "Good For Privacy",
        "special_features": "Good for Containers",
        "care_must_knows": "Pick limes when they're still green. They'll mature to a yellowish color, but may be too bitter. It usually takes about three to four months to develop their best flavor. Limes do not continue ripening after harvest and need to be stored in cool, high humidity conditions."
      },
      {
        
        "name": "Loquat Tree",
        "genus": "Eriobotrya japonica",
        "type": "Fruit",
        "light": "Part Sun",
        "description": "Glossy green leaves, sweetly fragrant flowers, and delicious fruit make loquat an all-star small tree. Grow it in the landscape, or plant it in a container to grow the tree as a patio plant. In the landscape, loquat grows to about 20 feet tall and has a round form. Its large leaves give it an unusual tropical texture. Loquats' fragrant flowers debut in fall. The autumn bloom is a welcome addition when many other plants are resting after a long season of flower production. The sweet, juicy fruits ripen in spring. Bees and wasps are attracted to fallen loquats. Plant the tree away from outdoor living areas to avoid these insects.Loquats grow best in full sun and well-drained soil. After establishing a strong root system, the trees tolerate dry conditions.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2016%2F02%2F31223854%2F101736319.jpg&q=85",
        "propagation": "Stem Cuttings",
        "height": "20 feet or more",
        "width": "To 15 feet wide",
        "flower_color": "White",
        "foliage_color": "None",
        "problem_solvers": "None",
        "special_features": "Low Maintenance",
        "care_must_knows": "Growing loquat fruit trees and their care focuses on good nutrition, water management and weed control. Fertilize the trees three times a year with a lawn fertilizer that does not contain weed killers. In the first year, use a cup (453.5 gr.) aof fertilizer divided into three applications spread over the growing season. In the second and third years, increase the annual amount of fertilizer to 2 cups (907 gr.). Scatter the fertilizer on the ground and water it in. Water a loquat tree when the blossoms begin to swell in spring and two to three more times when the fruit begins to ripen. Apply the water slowly, allowing it to sink into the soil as much as possible. Stop when the water begins to run off. Young trees don’t compete well with weeds, so maintain a weed-free area that extends 2 to 3 feet (60 to 91 cm.) from the trunk of the tree. Take care when cultivating around the tree because the roots are shallow."
      },
      {
        
        "name": "Nectarine",
        "genus": "Prunus persica nucipersica",
        "type": "Fruit",
        "light": "Sun",
        "description": "A nectarine is simply a fuzzless peach. Sweet and juicy, nectarines do not store for long periods of time, but they are especially flavorful and tasty when harvested right outside your back door. Choose a dwarf cultivar or prune trees regularly to maintain small trees for easy harvest.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2016%2F02%2F31223314%2FSIP949332.jpg&q=85",
        "propagation": "Grafting",
        "height": "3 to 8 feet",
        "width": "6-20 feet",
        "flower_color": "White",
        "foliage_color": "None",
        "problem_solvers": "None",
        "special_features": "None",
        "care_must_knows": "Nectarine trees bear in two to three years after planting. Fruits ripen in midsummer to midautumn, depending on the cultivar and zone. Pick them when all green coloration is gone. Ripe fruits easily come off the tree with a slight upward twist, but handle them gently because they bruise easily. Store ripe fruit in the refrigerator for a few days"
      },
      {
       
        "name": "Orange",
        "genus": "Citrus spp.",
        "type": "Fruit",
        "light": "Sun",
        "description": "Orange trees are a popular selection for gardeners in citrus-friendly climates. While grapefruits, mandarins, and acid fruits are also favored, sweet and juicy oranges are the most popular. In addition to producing tasty fruit, the trees have ornamental value, too. When in bloom they will perfume a landscape and a well-maintained tree makes a striking focal point. Plant an orange tree where it can be enjoyed from outdoor living spaces but far enough removed that any falling fruit will not create a messy problem.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2015%2F06%2F16025224%2F100958013.jpg&q=85",
        "propagation": "Grafting",
        "height": "8 to 20 feet",
        "width": "10-30 feet wide",
        "flower_color": "White",
        "foliage_color": "Blue/Green",
        "problem_solvers": "None",
        "special_features": "Fragrance",
        "care_must_knows": "Orange trees require a minimal amount of pruning. Clip away shoots that grow from the base of the tree. These shoots, called suckers, will interfere with tree development if not removed. Pruning in the canopy should be reserved to remove dead or rubbing branches or to prevent trees from crowding buildings or nearby plants. Make all pruning cuts flush with the trunk or surface to prevent rot and pest damage.Many orange trees benefit from regular fertilization. The tree's leaves and growth rate will indicate if fertilizer is needed. Trees planted in humus-rich soil are less likely to suffer from nutrient deficiencies than trees in sandy sites. Macro- and micronutrients are generally applied to citrus trees during their first few years after planting. High pH soil and iron deficiencies can be corrected through nutrition and fertilizer. Your extension service or local garden center can help address your tree's nutrient needs."
      },
      {
        
        "name": "Peach",
        "genus": "Prunus perscia",
        "type": "Fruit",
        "light": "Sun",
        "description": "The sweetest and juiciest peach you’ll ever taste can be picked from your own tree. When harvested at the peak of ripeness, backyard peaches are loaded with the sweet gifts of nature with no concern about shelf-stability or long transports. There are many easy-to-grow peach varieties. Grow your own with these simple tips.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2019%2F01%2F15213354%2FBHG116403.jpg&q=85",
        "propagation": "Grafting",
        "height": "3 to 8 feet",
        "width": "6-20 feet",
        "flower_color": "White",
        "foliage_color": "None",
        "problem_solvers": "None",
        "special_features": "None",
        "care_must_knows": "Plant container-grown peach trees anytime the ground is workable. Situate the plant in the ground so the top of the root ball is level with the surrounding grade. Water the newly planted tree generously, and continue watering weekly during the first growing season. Apply a 2- to 3-inch-thick layer of mulch over the root zone to help conserve soil moisture. These peach recipes will satisfy your sweet tooth with fresh flavor."
      },
      {
        "name": "Pear",
        "genus": "Pyrus communis",
        "type": "Fruit",
        "light": "Sun",
        "description": "Pears are among the easiest and most attractive fruit trees for the home landscape. Lovely even in winter, pears are easy to prune and can be trained into a formal or informal appearance. For small landscapes and easy harvest, choose a dwarf cultivar.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2016%2F02%2F31223806%2FSIP950021.jpg&q=85",
        "propagation": "Grafting",
        "height": "8 to 20 feet",
        "width": "8-25 feet",
        "flower_color": "White",
        "foliage_color": "None",
        "problem_solvers": "None",
        "special_features": "Fragrance",
        "care_must_knows": "Pyrus communis 'Hosui' produces a round pear with a snappy tang for its taste. The blight-resistant tree is self-pollinating. "
      },
      {
        "name": "Plum",
        "genus": "Prunus_ spp.",
        "type": "Fruit",
        "light": "Sun",
        "description": "Of all the stone fruits, plums are some of the most varied. They range from hardy little cherry plums and sand cherries to hybrids with the hardiness of natives, sweet European plums, and sweet or tart Japanese plums. Grow several different species and have fun comparing the fruits' taste and texture. You'll be surprised by the diversity. Plums are relatively easy to grow and the trees are a pleasing shape in the landscape.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2016%2F02%2F31223826%2FHGL100454.jpg&q=85",
        "propagation": "Grafting",
        "height": "8 to 20 feet",
        "width": "10-20 feet",
        "flower_color": "White",
        "foliage_color": "None",
        "problem_solvers": "None",
        "special_features": "None",
        "care_must_knows": "Plums bear their first crop of fruit 3 to 5 years after planting. Most trees are productive for 10 to 15 years. Plums are ready to harvest when they come off in your hand with a gentle twist. It has excellent hardiness and lovely golden-blushed red-skin fruit with yellow flesh. It is sweet and juicy."
      },
      {
       
        "name": "Raspberry",
        "genus": "Rubus",
        "type": "Fruit",
        "light": "Sun",
        "description": "Raspberries are an especially rewarding fruit to grow. They’re delightfully delicious, packed with nutrients and antioxidants, and easy to take care of. Plus, it’s so much easier to head out to the backyard for fresh fruit than running to the grocery store.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2015%2F06%2F16015914%2FSIP885311.jpg&q=85",
        "propagation": "Division",
        "height": "3 to 8 feet",
        "width": "3 to 8 feet",
        "flower_color": "White",
        "foliage_color": "Blue/Green",
        "problem_solvers": "None",
        "special_features": "Attracts Birds",
        "care_must_knows": "Plant breeders are working hard to make new varieties of raspberries better than ever. Look for newer types to be more compact, disease resistant, or hardy. Prune raspberries to keep them healthy and productive. It's best to do this in two waves. The first wave happens in spring and is called tip pruning. It simply means to cut off the top couple inches of new growth. This encourages your raspberries to produce more side branches—which means more fruit. The second wave of pruning happens in fall. Remove any stems that produced fruit; those stems won't produce fruit next year. Removing these spent stems will keep your blackberry patch from getting overgrown and can help reduce incidence of disease."
      },
      {
        
        "name": "Strawberry",
        "genus": "Fragaria spp.",
        "type": "Fruit",
        "light": "Sun",
        "description": "Dessert is right outside the door when you grow your own strawberries. Sweet and juicy homegrown berries are delicious in desserts, as well as the base for jams and jellies and for garnishing summer drinks and salads. Equally loved by deer, chipmunks, and a host of other rodents, strawberries need protection in areas that have high population of these critters. The effort is worth it when you harvest handfuls of sun-ripened berries.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2016%2F02%2F31230441%2F100175121.jpg&q=85",
        "propagation": "Division",
        "height": "Under 6 inches",
        "width": "18 inches",
        "flower_color": "White",
        "foliage_color": "Blue/Green",
        "problem_solvers": "Groundcover",
        "special_features": "None",
        "care_must_knows": "Plant strawberries in early spring as soon as the ground can be worked. Situate strawberry plants in the soil so their roots are fully covered with soil but the crown—or growing point where stems and leaves emerge—is sitting on top of the soil. Strawberries spread by runners that will emerge from the crown and create daughter plants nearby. Strawberry plants are often planted 18 to 30 inches apart in rows that are 3 to 4 feet apart. Runners extend from the plants to form daughter plants, increasing the width of the row. For best plant health and harvest, maintain rows that are no more than 2 feet wide. This planting method is called the matted row system. Strawberries grow best in full sun. A partly shaded planting area will greatly reduce berry production. Well-drained soil is essential. Wet or boggy soil will limit plant growth and increase the potential for berries to rot after ripening. If your landscape is plagued by poorly drained soil, plant strawberries in a raised bed."
      },
      {
        "name": "Barberry",
        "genus": "Berberis",
        "type": "Shrub",
        "light": "Part Sun",
        "description": "Barberry shines throughout the entire growing season with its vibrant foliage. In shades of green, yellow, and rich burgundy, these plants make up for their lack of showy blooms with their constantly colorful leaves. Although these tough hedge plants used to be planted frequently, they are now considered invasive plants in several regions. So if you are thinking of planting a barberry, make sure to check with your local authorities (most states issue invasive plant lists you shouldn't grow).",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2020%2F08%2F17%2Fbarberry-plants-lawn-2fe0ce25.jpg&q=85",
        "propagation": "Seed",
        "height": "3 to 8 feet",
        "width": "Up to 7 feet",
        "flower_color": "Yellow",
        "foliage_color": "Blue/Green",
        "problem_solvers": "Deer Resistant",
        "special_features": "Low Maintenance",
        "care_must_knows": "One of the main reasons this shrub has persisted is because it is a tough plant that can take a wide variety of conditions. Ideally, barberries prefer to live in full sun; they will perform their best and give the most color in this setting. However, they are tough enough that they can even perform well in part sun. Well-drained soil is also appreciated, as they don't like to have wet feet. In addition, protect your shrubs from winter damage.\nWhen looking at varieties, make sure to keep an eye on overall size and habit of these shrubs. Some of the older varieties can get quite large and may require extra pruning, but that can be prevented by choosing a smaller variety. It is also key to note that many varieties can spread by underground runners and may form dense thickets"
      },
      {
    
        "name": "Wintergreen",
        "genus": "Gaultheria procumbens",
        "type": "Shrub",
        "light": "Part Sun",
        "description": "Wintergreen has caught the eye of plant scientists and landscape designers. It is a hardworking landscape problem solver in cool, shaded planting sites. Wintergreen has evergreen leaves paired with white flowers in summer and bright red berries in fall. Standing just 6 inches tall, it hugs the ground, choking out weeds while creating a dense mat of glossy foliage.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2016%2F02%2F15224559%2F101346874.jpg&q=85",
        "propagation": "Division",
        "height": "Under 6 inches",
        "width": "To 36 inches wide",
        "flower_color": "White",
        "foliage_color": "None",
        "problem_solvers": "Groundcover",
        "special_features": "Attracts Birds",
        "care_must_knows": "Plant wintergreen in spring or early summer. Water plants thoroughly and frequently through the first growing season after planting. Reduce watering during the second season, but water generously during prolonged periods of drought. Blanket the ground around plants with a 2-inch-thick layer of shredded-bark mulch to slow soil moisture loss. Wintergreen spreads moderately by underground rhizomes to form a dense mat. Prune plants as needed in winter."
      },
      {
        "name": "Coconut Palm Tree",
        "genus": "Cocos nucifera",
        "type": "Tree",
        "light": "Sun",
        "description": "Coconut palm is the most recognizable palm in the world. This tree grows 60-100 feet tall and 20-30 feet wide with huge leaves to 15 feet long. Coconut fruits hang in clusters under and among leaf bases. Immature fruits range in color from green to yellow or red, but all eventually turn brown. This palm is extremely drought-tolerant and can withstand salty soils.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2016%2F02%2F31223816%2F100146355.jpg&q=85",
        "propagation": "Seed",
        "height": "20 feet or more",
        "width": "20-30 feet wide",
        "flower_color": "None",
        "foliage_color": "None",
        "problem_solvers": "Drought Tolerant",
        "special_features": "None",
        "care_must_knows": "Cocos nucifera 'Panama Tall' is also known as Pacific Tall coconut. It grows rapidly up to 100 feet tall and forms a large-diameter trunk. Immature fruits are either green or bronze colored. Zones 10-11"
      },
      {
        "name": "Crabapple Tree",
        "genus": "Malus",
        "type": "Tree",
        "light": "Sun",
        "description": "Clusters of fragrant pom-pom spring flowers, striking fall foliage, and dangling winter fruits that attract birds make crabapple a splendid landscape tree. Add small stature to the list of attributes and you have a fitting choice for landscapes of many different sizes. Popular in Midwest landscapes where it is hardy, this deciduous tree typically grows 10 to 20 feet tall and wide. Plant breeders continuously work to develop new varieties, some maturing at less than 10 feet tall.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2020%2F02%2Fprairie-fire-crabapple-tree-90d74cb8.jpg&q=85",
        "propagation": "Grafting",
        "height": "8 to 20 feet",
        "width": "15-25 feet wide",
        "flower_color": "White",
        "foliage_color": "None",
        "problem_solvers": "Good For Privacy",
        "special_features": "Attracts Birds",
        "care_must_knows": "Although it's easy to fall in love with crabapple, it's important to remember that plant diversity is important to a thriving ecosystem. A mix of small woody species is more valuable to local wildlife than a crabapple monoculture. Plant two or three crabapple trees alongside redbud, viburnum, lilac, dogwood, magnolia, juniper, holly, and/or cotoneaster. Create a living fence by planting crabapple trees along with other flowering shrubs and evergreens along a property line. Crabapple trees also make excellent specimen plants. Anchor the corner of a foundation bed with a low-branching, spreading cultivar. Add a crabapple to a perennial border for vertical interest year-round."
      },
      {
       
        "name": "Date Palm Tree",
        "genus": "Phoenix spp.",
        "type": "Tree",
        "light": "Sun",
        "description": "Date palm, which is grown by home gardeners primarily for its decorative fronds (not its fruit), is cultivated as a landscape tree in Zones 9 to 11 in the United States. Growing this tree in Zone 8 requires a sheltered location to prevent it from being damaged by freezing weather.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2020%2F12%2F01%2Fmain-canary-island-date-palm-tree-d5024cb1.jpg&q=85",
        "propagation": "Seed",
        "height": "20 feet or more",
        "width": "20-40 feet wide",
        "flower_color": "None",
        "foliage_color": "None",
        "problem_solvers": "Drought Tolerant",
        "special_features": "None",
        "care_must_knows": "Slow-growing date palm grows best in rich, well-drained soil in full sun (although light shade is tolerated). Deep, even moisture is best for this plant. If well-established, date palm will tolerate drought. But it's likely to suffer significant frond damage or even die if temperatures fall beneath 20 degrees Fahrenheit. If conditions are just right, and they get a little help from brooks, streams, other water channels, or birds, some date palms can naturalize to the point of being invasive."
      },
      {
        
        "name": "Flowering Cherry Tree",
        "genus": "Prunus spp.",
        "type": "Tree",
        "light": "Sun",
        "description": "Flowering cherry trees are among the showiest and most dramatic trees that can be grown in your home landscape. They burst into bloom after a long winter, practically covering their branches with confetti-like flowers in shades of pink or white. The flowers of the many varieties are both attractive and fragrant.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2016%2F02%2F31230859%2FBHG196685.jpg&q=85",
        "propagation": "Grafting",
        "height": "8 to 20 feet",
        "width": "10-30 feet wide",
        "flower_color": "White",
        "foliage_color": "Blue/Green",
        "problem_solvers": "None",
        "special_features": "Attracts Birds",
        "care_must_knows": "A late-flowering cultivar with bright white, double flowers, 'Icicle' is an eye-catching plant in bloom. Prune it regularly to maintain a pleasing form. Zone 6"
      },
      {
       
        "name": "American Persimmon Tree",
        "genus": "Diospyros virginiana",
        "type": "Tree",
        "light": "Sun",
        "description": "American persimmon is a tall shade tree that's sadly underused in gardens. It features dark green foliage that often develops yellow or red tones in fall. Older trees have distinctive bark that almost looks scaly, as though it's covered in small silvery plates.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2016%2F02%2F31225411%2F101503125.jpg&q=85",
        "propagation": "Seed",
        "height": "20 feet or more",
        "width": "To 35 feet wide",
        "flower_color": "None",
        "foliage_color": "Chartreuse/Gold",
        "problem_solvers": "Good For Privacy",
        "special_features": "Attracts Birds",
        "care_must_knows": "None"
      },
      {
        
        "name": "Loquat Tree",
        "genus": "Eriobotrya japonica",
        "type": "Tree",
        "light": "Part Sun",
        "description": "Glossy green leaves, sweetly fragrant flowers, and delicious fruit make loquat an all-star small tree. Grow it in the landscape, or plant it in a container to grow the tree as a patio plant. In the landscape, loquat grows to about 20 feet tall and has a round form. Its large leaves give it an unusual tropical texture. Loquats' fragrant flowers debut in fall. The autumn bloom is a welcome addition when many other plants are resting after a long season of flower production. The sweet, juicy fruits ripen in spring. Bees and wasps are attracted to fallen loquats. Plant the tree away from outdoor living areas to avoid these insects.Loquats grow best in full sun and well-drained soil. After establishing a strong root system, the trees tolerate dry conditions.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2016%2F02%2F31223854%2F101736319.jpg&q=85",
        "propagation": "Stem Cuttings",
        "height": "20 feet or more",
        "width": "To 15 feet wide",
        "flower_color": "White",
        "foliage_color": "None",
        "problem_solvers": "None",
        "special_features": "Low Maintenance",
        "care_must_knows": "None"
      },
      {
        
        "name": "Serviceberry Tree",
        "genus": "Amelanchier",
        "type": "Tree",
        "light": "Part Sun",
        "description": "This small tree thrives through all four seasons and offers so much to any garden. Abundant white blooms in spring are followed by delicious berries in summer, fiery foliage in fall, and silver bark in winter.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2020%2F03%2Fautumn-brilliance-serviceberry-268b68ac.jpg&q=85",
        "propagation": "Seed",
        "height": "8 to 20 feet",
        "width": "4 to 15 feet wide",
        "flower_color": "White",
        "foliage_color": "None",
        "problem_solvers": "Drought Tolerant",
        "special_features": "Low Maintenance",
        "care_must_knows": "Serviceberry trees display white blooms just before their foliage emerges in early spring, offering some of the earliest sources of nectar for pollinators. The five-petaled flowers closely resemble apple blossoms but with skinnier petals."
      },
      {
        
        "name": "Watermelon",
        "genus": "Citrullus lanatus",
        "type": "Fruit",
        "light": "Sun",
        "description": "Watermelons range from single serving types to mammoth fruits that can feed an entire little league team. These vining plants need some room to sprawl, though some newer varieties feature more compact growth for small space gardens. All thrive in areas with long, hot summers, and will reward your patience with their juicy, garden-fresh fruits.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2020%2F04%2F30%2Fstack-of-picked-watermelons-92e16796.jpg&q=85",
        "propagation": "Seed",
        "height": "1 to 3 feet",
        "width": "5-20 feet wide",
        "flower_color": "None",
        "foliage_color": "None",
        "problem_solvers": "None",
        "special_features": "None",
        "care_must_knows": "Watermelons grow best in long, hot summers. If summers are short or cool, consider laying black plastic over the soil for insulation. Make several holes in the cover to allow moisture to reach plant roots. If insect pests are a problem, consider covering young plants with row covers. Remove the row covers when watermelon vines begin blooming as row covers prevent pollination. Water young plants regularly to encourage good growth and fruit development. Reduce watering as fruits ripen for the best sweet flavor."
      },
      {
        
        "name": "Black-Eyed Susan Vine",
        "genus": "Thunbergia",
        "type": "Annual",
        "light": "Sun",
        "description": "An old-fashioned favorite, black-eyed Susan vine is beloved for cheerful yellow blossoms that unfurl with abandon from midsummer until the first frost. A little slow to get started in spring and early summer, black-eyed Susan begins to grow with gusto at a time when many perennials and some annuals take a midsummer break. This climbing plant will quickly ramble up a short trellis and is especially striking when trailing from a window box or hanging basket.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2016%2F02%2F31225449%2FSIP926564.jpg&q=85",
        "propagation": "Seed",
        "height": "3 to 8 feet",
        "width": "Climbs to 8 feet",
        "flower_color": "Orange",
        "foliage_color": "Chartreuse/Gold",
        "problem_solvers": "None",
        "special_features": "Low Maintenance",
        "care_must_knows": "This variety of Thunbergia alata offers big yellow flowers with brown centers. It climbs to 8 feet. Zone 10-11, but it's usually grown as an annual."
      },
      {
        "name": "Hops",
        "genus": "Humulus lupulus",
        "type": "Vine",
        "light": "Part Sun",
        "description": "Hops is widely grown as a key ingredient in beer making, but this perennial vine is also beautiful, making it an excellent ornamental. The hops used in beer making are the seed heads of the vine. Because the plant has separate sexes, you'll need to plant a female vine to get the hops and a male plant to pollinate. Harvest hops when they feel light and dry to the touch. Vines grow vigorously, so provide a sturdy trellis. Prune hops back to the ground every spring.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2016%2F07%2F15215309%2F101620526.jpg&q=85",
        "propagation": "Layering",
        "height": "8 to 20 feet",
        "width": "6-20 feet wide",
        "flower_color": "None",
        "foliage_color": "None",
        "problem_solvers": "None",
        "special_features": "Low Maintenance",
        "care_must_knows": "Humulus lupulus 'Aureus' has chartreuse foliage. It is grown as an ornamental vine for its lobed yellow-green leaves. It also bears small greenish-white flowers that attract butterflies. In the North, it can withstand full sun, but foliage may scorch without afternoon shade in warm climates. Zones 4-9"
      },


]