const vegetables = [
    {
        
        "name": "Kale",
        "genus": "Brassica oleracea var. acephala",
        "type": "Vegetable",
        "light": "Sun",
        "description": "Kale, a hardy leafy green, is not only a superfood but also a super producer. This cool-weather vegetable tolerates frost with ease and produces tender and succulent upright leaves well into fall. Plant kale in early spring in a traditional garden or a container to enjoy its leaves for five months or more. Kale thrives in full sun but grows well in part shade. From a balcony garden to a suburban raised bed, kale will grow nearly anywhere.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2016%2F02%2F31230423%2F100229893.jpg&q=85",
        "propagation": "Seed",
        "height": "1 to 3 feet",
        "width": "1 to 3 feet wide",
        "flower_color": "None",
        "foliage_color": "Purple/Burgundy",
        "problem_solvers": "None",
        "special_features": "None",
        "care_must_knows": "Kale grows best in full sun and moist, well-drained soil. Although kale leaves acquire their best flavor after autumn's first frost, this plant can also be grown in early spring. Start it from seed indoors about eight weeks before the last average frost date. Those seedlings—or transplants from the garden center—can be planted in the garden a couple of weeks after all danger of frost is past.\n\nIn cold climates, sow seeds outside as soon as the soil reaches 45 degrees F and the ground can be worked. Sow seeds 2 inches apart in rows 2 to 18 inches apart. Plant seeds ½ inch deep and keep soil evenly moist to ensure good germination. In warm climates, harvest a fall drop by planting seeds inside by early July, then transplanting the seedlings outside in the garden by mid-August. Water the plants well, as moist soil helps keep the leaves sweet and crisp instead of bitter.\nCare for crops planted in late summer by mulching around plants to delay the ground from freezing around roots. Pull and discard plants as soon as they begin to flower; those leaves are tough and bitter."
      },
      {
        
        "name": "Kohlrabi",
        "genus": "Brassica oleracea Gongylodes group",
        "type": "Vegetable",
        "light": "Sun",
        "description": "Kohlrabi is a nutritious vegetable that’s often overlooked in edible gardens. That’s too bad because this plant offers a delicious taste and interesting appearance, and it’s a cinch to grow. This cabbage relative develops a swollen, bulblike stem from which its textural gray-green leaves sprout. Its interesting look and easy-to-grow nature make this vegetable good for a garden tended by children to help develop the next generation’s love of fresh food and gardening.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2016%2F02%2F31225943%2F100329025.jpg&q=85",
        "propagation": "Seed",
        "height": "6 to 12 inches",
        "width": "10 to 12 inches wide",
        "flower_color": "Yellow",
        "foliage_color": "Blue/Green",
        "problem_solvers": "None",
        "special_features": "Good for Containers",
        "care_must_knows": "Plant kohlrabi in a sunny spot that gets half-day or all-day sun and moist but well-drained soil in early spring or autumn. It's usually planted from seed, but you may be able to find young plants started and ready to go at your local garden center. It tolerates frost, so you can plant it a couple of weeks before your area's last expected frost date in spring. Transplant fall crops of kohlrabi outdoors in the ground in mid- to late August."
      },
      {
       
        "name": "Leek",
        "genus": "Allium porrum",
        "type": "Vegetable",
        "light": "Sun",
        "description": "Leeks are like delicate onions. They add their rich but subtle flavor to everything from creamy sauces to soups and stews. They're a must for any food enthusiast's garden.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2016%2F02%2F31224616%2F100906670.jpg&q=85",
        "propagation": "Seed",
        "height": "6 to 12 inches",
        "width": "1-2 inches wide",
        "flower_color": "None",
        "foliage_color": "None",
        "problem_solvers": "None",
        "special_features": "None",
        "care_must_knows": "Allium porrum 'King Richard' is a tall, thin variety that matures just 75 days after transplanting."
      },
      {
        "name": "Lettuce",
        "genus": "Lactuca sativa",
        "type": "Vegetable",
        "light": "Part Sun",
        "description": "There’s no need to wait until tomatoes ripen in summer to embrace garden-to-table deliciousness. That’s because lettuce, a suitable plant for small-space gardens, is exceptionally easy to grow in cool weather. Plant lettuce in early spring and your table will overflow with tender, flavorful greens 6-8 weeks later.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2020%2F04%2F17%2Ftango-oakleaf-lettuce-c6f6417e.jpg&q=85",
        "propagation": "Seed",
        "height": "Under 6 inches",
        "width": "2-12 inches wide",
        "flower_color": "None",
        "foliage_color": "None",
        "problem_solvers": "None",
        "special_features": "None",
        "care_must_knows": "Head lettuces, such as butterhead, crisphead, iceberg, and romaine, develop into upright clumps that are loosely packed or tightly bunched. Plant head lettuces outside in early spring where they will receive full sun. Sow seeds ¼ inch deep and 2 inches apart in rows 6 to 8 inches apart. Keep the seedbed evenly moist. Gradually thin the seedlings so the remaining plants are 12 inches or so apart. The thinned seedlings can be harvested and enjoyed as baby lettuces."
      },
      {
               "name": "Lima Bean",
        "genus": "Phaseolus lunatus",
        "type": "Vegetable",
        "light": "Sun",
        "description": "If its name sets off less-than-pleasant childhood memories for you, you'll develop a new appreciation for this nutrient-rich vegetable when you grow it yourself. A close relative of snap beans, this warm-season crop is easy to start from seed planted right in the garden. Plus, it’s a good producer. Enjoy lima beans fresh by picking pods when they are full and bright green, or allow beans to dry on the plant and harvest dried beans for use during the cooler months.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2020%2F04%2F16%2Flima-beans-phaseolus-lunatus-5e580016.jpg&q=85",
        "propagation": "Seed",
        "height": "1 to 3 feet",
        "width": "18-30 inches wide",
        "flower_color": "None",
        "foliage_color": "None",
        "problem_solvers": "None",
        "special_features": "None",
        "care_must_knows": "Lima beans grow best when temperatures are between 70 and 80 degrees F and they get 1 inch of water per week either from rain or irrigation. Hot, dry conditions during flowering may cause the flowers to drop off without setting pods. Lima beans may flower again when temperatures drop. There is no need to fertilize plants. In fact, excessive nitrogen fertilizer can prevent pods from forming even though it also promotes lush growth."
      },
      {
        
        "name": "Malabar Spinach",
        "genus": "Basella alba",
        "type": "Vine",
        "light": "Sun",
        "description": "Enjoy homegrown, nutrient-packed greens all summer long with Malabar spinach. This heat-loving tropical vine grows with gusto while its cool-temperature-loving counterparts are turning bitter and heading for the compost pile. Thanks to heart-shape dark green leaves that taste like spinach and provide calcium, iron, and vitamins A and C, this vine is both nutritious and decorative. Grow it on a sturdy trellis, and it will provide structure in the garden along with bounty for the table. It also thrives in large containers or hanging baskets.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2016%2F02%2F31230415%2F101048335.jpg&q=85",
        "propagation": "Seed",
        "height": "1 to 3 feet",
        "width": "2 to 3 feet wide",
        "flower_color": "Purple",
        "foliage_color": "Blue/Green",
        "problem_solvers": "None",
        "special_features": "None",
        "care_must_knows": "Shortly after planting, provide a sturdy climbing support—trellis, arbor, or fence—for your vining plants. (Two plants will serve a family's vegetable needs for the summer and fall growing season.) Once the vines begin to grow, weave them around the support so they can climb up the structure. Begin harvesting young leaves and tender shoot tips—which will be more tender than mature ones—about 55 days after seeding. Continue harvesting through summer."
      },
      {
       
        "name": "Melon",
        "genus": "Cucumis melo",
        "type": "Vegetable",
        "light": "Sun",
        "description": "Long, hot summers with ample moisture yield juicy, flavor-rich melons with a high sugar content. Not all regions provide the necessary long stretch of warm weather and adequate moisture to grow great melons. But if you live in a region that does, plant some seeds and get ready for a bountiful harvest. Melons don’t all ripen at the same time, so you will enjoy a long season of harvest with many fruits to share with friends and family.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2020%2F07%2F13%2Fmelon-cucumis-melo-47c8b217.jpg&q=85",
        "propagation": "Seed",
        "height": "1 to 3 feet",
        "width": "5-20 feet wide",
        "flower_color": "None",
        "foliage_color": "None",
        "problem_solvers": "None",
        "special_features": "None",
        "care_must_knows": "Melon grows best in full sun and moist, well-drained soil. Plants thrive when they receive at least 8 hours of direct sunlight a day. Quick-draining soil is also essential. Not only will seedlings struggle to get established in clay and slow-draining soil, but fruit that develops will have a higher chance of rotting when it sits on moist soil. Plant melons in raised beds if drainage is a problem.\n\nStart melons from seed planted directly in the garden after the last chance of frost passes. Melon seed germinates when the soil temperature is above 65ºF. Seeds planted in cold soil are more likely to suffer from disease and rot. Sow seeds in group of two or three anywhere between 18 to 24 inches apart. Space rows 5 to 6 feet apart. After the seedlings emerge, choose the strongest plant and remove the others. Melons produce long vining stems. Be sure to give them plenty of space to spread in the garden.\nMelons can also be started from transplants purchased at the garden center or from transplants started indoors 6 to 8 weeks before the last spring frost. Melon transplants are sensitive to root disturbance. Transplant young plants carefully to prevent breaking or damaging the roots. Water melons carefully. Plants demand 1 to 2 inches of water per week during the peak growing season. Water plants with a drip or soaker hose, saturating the soil but keeping the foliage dry. Gradually reduce watering as the fruit ripens. Too much watering during the last two weeks of ripening can cause the fruits to split."
      },
      {
        "name": "New Zealand Spinach",
        "genus": "Tetragonia tetragonioides",
        "type": "Vegetable",
        "light": "Sun",
        "description": "Like Malabar spinach, New Zealand spinach is a great way to enjoy a tender green even in the heat of summer, when regular spinach doesn't grow well. In the warmest regions of the United States, it can be grown as a perennial, but in most regions it grows best as a warm-season annual.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2016%2F02%2F31224735%2F101025501.jpg&q=85",
        "propagation": "Seed",
        "height": "1 to 3 feet",
        "width": "1-3 feet wide",
        "flower_color": "None",
        "foliage_color": "None",
        "problem_solvers": "None",
        "special_features": "None",
        "care_must_knows": "Plant New Zealand spinach in full sun. New Zealand spinach prefers moisture-retentive, well-drained soil rich in organic matter. New Zealand spinach is weak-stemmed and will appear to trail across the garden. Set plants in hills similar to squash. New Zealand spinach prefers a soil pH of 6.8 to 7.0. Prepare planting beds with well-aged compost. Where summer heat is intense, plant New Zealand spinach where it will get partial shade in the afternoon. Sow New Zealand spinach ½ inch (12mm) deep and 2 to 4 inches (5-10cm) apart. New Zealand spinach grows from seed clusters that produce several seedlings, similar to beet seed. Soak seeds overnight in water to speed germination. When seedlings are 3 inches (7cm) tall, thin to the strongest seedlings, from 12 to 18 inches (30-45cm) apart. Set New Zealand spinach in hills similar to squash. This will allow the weak-stem to sprawl. Space hills or rows 24 to 36 inches (61-91cm) apart."
      },
      {
        "name": "Okra",
        "genus": "Abelmoschus esculentus",
        "type": "Vegetable",
        "light": "Sun",
        "description": "Traditionally a favorite in the South, okra is growing more popular in home gardens everywhere. It’s easy to learn why. Okra is a nutritious vegetable that’s easy to grow and ornamental—what’s not to love?",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2015%2F06%2F16003317%2F101074395.jpg&q=85",
        "propagation": "Seed",
        "height": "3 to 8 feet",
        "width": "3 to 4 feet wide",
        "flower_color": "Yellow",
        "foliage_color": "Blue/Green",
        "problem_solvers": "None",
        "special_features": "Good for Containers",
        "care_must_knows": "Okra is an annual vegetable that loves summer heat. Whether you grow it from seed or buy transplants, you'll find it does best if you wait to plant it outdoors until night temperatures reliably stay above 55°F."
      },
      {
       
        "name": "Onion",
        "genus": "Allium cepa",
        "type": "Vegetable",
        "light": "Sun",
        "description": "The onion is an easy-to-grow vegetable that’s big on flavor. Whether you grow sweet onions or storage onions, fresh onions are delicious on salads, sautéed, or caramelized in a variety of savory dishes. Plant a diverse crop of onions, including a variety or two that stores well, and enjoy garden-fresh onions year-round. Full sun and moist, well-drained soil are all you need for a prolific onion crop.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2019%2F01%2F15220349%2FMWL408500.jpg&q=85",
        "propagation": "Seed",
        "height": "6 to 12 inches",
        "width": "1-5 inches wide",
        "flower_color": "None",
        "foliage_color": "None",
        "problem_solvers": "None",
        "special_features": "None",
        "care_must_knows": "Allium cepa 'Copra Hybrid' is a widely adapted long-day yellow storage onion that is sweeter than most other storage onions. Onions can be started from seed or from sets (tiny bulbets). With seeds you have more choice of varieties, and you can choose varieties that are suited to your region. (In the North, plant long-season onions in the spring; in the South, short season onions, planted in the fall, are best.)\nStart your seeds, transplant into larger cells, and before planting out, harden them off by putting the pots outside for several days. In the garden, onion plants should be spaced 4 to 6 inches apart in the row, with rows 1 to 2 feet apart. Plant each one about 1/2 inch deep in a small hole. After planting, trim the tops to about 4 inches.\nOnions need about 1 inch of water per week, so if the weather is dry, you’ll need to water."
      },
      {
       
        "name": "Parsnip",
        "genus": "Pastinaca sativa",
        "type": "Vegetable",
        "light": "Sun",
        "description": "Parsnip is a vegetable that might not sound exciting, but it's absolutely delicious in soups and stews, where it adds a sweet note. Parsnips are also great boiled and mashed up with potatoes, adding sweetness and depth to that classic dish.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2016%2F02%2F31224822%2F101127009.jpg&q=85",
        "propagation": "Seed",
        "height": "6 to 12 inches",
        "width": "6-12 inches wide",
        "flower_color": "None",
        "foliage_color": "None",
        "problem_solvers": "None",
        "special_features": "None",
        "care_must_knows": "Pastinaca sativa 'Andover' is a productive variety with long, cylindrical roots and a rounded crown. It has good resistance to canker. Expose plants to 2-4 weeks of low temperatures before harvest to build up the sugar content of the roots. In warm areas, you can harvest roots all winter. In colder regions, you can mulch the bed with several inches of straw and harvest in early spring before plants start to grow again"
      },
      {
        
        "name": "Pea",
        "genus": "Pisum sativum",
        "type": "Vegetable",
        "light": "Sun",
        "description": "Peas are a spring garden staple, loved for their easy-to-grow nature, delicious seeds, and nutritional value. There’s something magical about harvesting peas fresh from the garden and tasting their sweet, fresh flavor.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2016%2F02%2F31230214%2F100331359.jpg&q=85",
        "propagation": "Seed",
        "height": "1 to 3 feet",
        "width": "6-12 inches wide",
        "flower_color": "White",
        "foliage_color": "Blue/Green",
        "problem_solvers": "None",
        "special_features": "Good for Containers",
        "care_must_knows": "Like most vegetables, peas do best in a spot with full sun (at least 6 to 8 hours of direct light per day). Water peas regularly to keep the soil moist but not wet and soggy. If your yard has clay soil, amending liberally with organic matter can help produce better harvests and reduce the chance of seeing root rot in periods of wet weather. You can also grow peas in containers or raised beds to offer the conditions they need to thrive. Growing them in containers or raised beds makes them easier to harvest, too, as you don't need to bend down as far to pluck the pods from the plants."
      },
      {
        
        "name": "Peanuts",
        "genus": "Arachis hypogaea",
        "type": "Vegetable",
        "light": "Sun",
        "description": "Growing and harvesting peanuts is a little like hosting your own treasure hunt. These warm season plants are easy to grow in areas with long, hot summers and moist, well-drained soil. When the peanut foliage turns yellow, it’s time to go on a dig for your treasure. The underground nuts are ready to eat a few weeks after digging and drying. Grow peanuts in the vegetable garden where the soil is loose and moist.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2016%2F02%2F31225512%2F101126992.jpg&q=85",
        "propagation": "Seed",
        "height": "1 to 3 feet",
        "width": "1-3 feet wide",
        "flower_color": "None",
        "foliage_color": "None",
        "problem_solvers": "None",
        "special_features": "None",
        "care_must_knows": "Peanuts grow best in full sun and well-drained soil. This root crop languishes in clay and poorly drained soil. Plant peanuts after the danger of frost has passed and soil is at least 65°F. Sow seeds 1 to 1½ inches deep and 6 to 8 inches apart. Row spacing for bunch types should be about 24 inches apart, and 36 inches apart for runner types.\n\nPeanut plants bloom about 30 to 40 days after germination. After pollination, peanuts develop in 9 to 10 weeks. Peanut plants flower over a period of several weeks, meaning all the pods do not mature at the same time. Promote a strong peanut crop by cultivating around plants to remove weeds. Work carefully and shallowly, being careful not to damage peanut roots.\nHarvest peanuts when the foliage begins to turn yellow. Use a spading fork to gently lift the peanut plants out of the ground. Shake off loose soil. Cure or dry plants by hanging them in a warm, dry, shaded place, such as a shed or garage, for about two weeks. After 2 weeks shake off any remaining soil and pull peanuts pods from the plants. Continue to air-dry the peanuts for an additional 1 to 2 weeks."
      },
      {
        "name": "Pumpkin",
        "genus": "Cucurbita maxima",
        "type": "Vegetable",
        "light": "Sun",
        "description": "From giant pumpkins that weigh hundreds of pounds to miniature pumpkins that fit neatly in the palm of your hand, there’s a pumpkin for every gardener. Growing pumpkins is easy, though it can require ample space. There’s a reason they call it a pumpkin patch: These autumn treasures need room and grow several feet out in all directions. Traditional orange jack-o’-lantern pumpkins are a top choice for carving, but it’s also fun to try other colors: white, buff, blue-green, and scarlet.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2020%2F04%2F29%2Fvariety-orange-yellow-white-pumpkins-eb4d1c60.jpg&q=85",
        "propagation": "Seed",
        "height": "1 to 3 feet",
        "width": "3 to 15 feet wide",
        "flower_color": "Yellow",
        "foliage_color": "Blue/Green",
        "problem_solvers": "None",
        "special_features": "Low Maintenance",
        "care_must_knows": "If you want good harvests, be sure to plant pumpkins in full sun (at least 6 to 8 hours of direct sun per day) with well-draining soil. If your ground has a high sand or clay content, amend it liberally with organic matter such as compost, peat, or coir to fuel your pumpkin plants' rampant growth. This is especially important if you're growing giant varieties.\n\nBecause pumpkins are heat-loving plants, place seeds or transplants outdoors after soil temperatures remain above 60 degrees F. If you put them out too early and it's still cold, your seeds or young plants will sulk in cool weather and potentially rot before they grow. If you're in a short-summer area, start your pumpkin seeds indoors three to four weeks before you'd normally plant them outdoors to get a head start on the season.\nIf you grow pumpkins in rows, space your plantings 3-6 feet apart. Protect pumpkins from pests like squash vine borers by using floating row covers in spring until the plants grow too large for them.\nLeave pumpkins on the vine until the skin turns the appropriate color for the variety and the rind feels hard when pressed with your thumbnail. Harvest before a hard frost by cutting the stem from the vine with a sharp knife, leaving a 2-inch stub on the fruit. Place the harvested pumpkins at 80° to 85°F for two weeks to cure them. For longer term storage, place them in a dark location at 50° to 55°F."
      },
      {
        "name": "Saffron",
        "genus": "Crocus sativus",
        "type": "Bulb",
        "light": "Part Sun",
        "description": "Whether you call it an herb or a spice, saffron is made from the dried stigmas of one fall-blooming crocus species. This precious herb can be worth thousands of dollars per pound. Grow your own crop for significant savings in making your own paella. Plant this crocus in early fall; the corms will bloom 6-8 weeks later if the bulbs are planted 3-4 inches deep and about 2 inches apart. Saffron grows best in full sun in well-drained soil.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2016%2F02%2F31223752%2F101829827.jpg&q=85",
        "propagation": "Division",
        "height": "Under 6 inches",
        "width": "1-3 inches wide",
        "flower_color": "Blue",
        "foliage_color": "None",
        "problem_solvers": "Drought Tolerant",
        "special_features": "Cut Flowers",
        "care_must_knows": "None"
      },
      {
        "name": "Scented Geranium",
        "genus": "Pelargonium",
        "type": "Annual",
        "light": "Part Sun",
        "description": "These plants have been favorites of herb and indoor gardeners since Victorian times. With fragrances of fruits, flowers, spices, or even chocolate, scented geraniums delight the senses. Brush against the leaves to release their strong aroma. Their tactile leaves can be fuzzy or smooth, and they come in a wide range of shapes and hues. Most varieties also have small clusters of pale pink or white flowers in summer.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2020%2F04%2F14%2Fscented-geranium-plant-5b2805fc.jpg&q=85",
        "propagation": "Division",
        "height": "1 to 3 feet",
        "width": "1-2 feet wide",
        "flower_color": "White",
        "foliage_color": "Blue/Green",
        "problem_solvers": "None",
        "special_features": "Fragrance",
        "care_must_knows": "Scented geraniums may be grown as annuals or they can be overwintered and enjoyed year after year. There are several ways to successfully overwinter scented geraniums. Overwinter them as a houseplant by bringing containers indoors in fall before frost and placing plants in a bright, sunny window. Reduce watering plants while they are indoors, allowing the soil around the roots to dry before watering. Or, you can overwinter scented geraniums as dormant plants by bringing container-planted specimens indoors before the first frost and storing them in a dark corner of a basement or in a frost-free garage. Allow the plant to go dormant by not watering during winter. Bring plants outside when the last chance of frost passes in spring."
      },
      {
        "name": "Sweet Cicely",
        "genus": "Myrrhis odorata",
        "type": "Herb",
        "light": "Part Sun",
        "description": "Sweet cicely is one of the few herbs that thrives in the shade. It prefers moist soil and cool temperatures. All parts of sweet cicely are edible and impart a slight anise flavor to recipes. Use the leaves either fresh or dried in salads. Seeds are sometimes substituted for caraway; roots may be peeled, boiled, and eaten as a vegetable. The plant grows 3 feet tall and wide with fernlike foliage. In late spring, sweet cicely bears clusters of attractive white flowers.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2016%2F02%2F31224021%2F101620471.jpg&q=85",
        "propagation": "Seed",
        "height": "3 to 8 feet",
        "width": "30-36 inches wide",
        "flower_color": "White",
        "foliage_color": "None",
        "problem_solvers": "None",
        "special_features": "Fragrance",
        "care_must_knows": "None"
      },
      {
        "name": "Sweet Grass",
        "genus": "Hierochloe odorata",
        "type": "Herb",
        "light": "Part Sun",
        "description": "Also called holygrass or bisongrass, sweetgrass is a native prairie grass prized for its fresh scent. It grows naturally in meadows and along stream banks. Native American tribes have long used sweetgrass for making smudge sticks as well as for weaving baskets. The plant spreads up to 2 feet wide annually, so plant it where it can be confined. It eventually forms a thick mat of foliage that tends to flop over unless cut back.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2016%2F02%2F15215850%2F101620487.jpg&q=85",
        "propagation": "Division",
        "height": "1 to 3 feet",
        "width": "12-24 inches wide",
        "flower_color": "None",
        "foliage_color": "None",
        "problem_solvers": "Groundcover",
        "special_features": "Low Maintenance",
        "care_must_knows": "None"
      },
      {
       
        "name": "Tarragon",
        "genus": "Artemisia dracunculus",
        "type": "Perennial",
        "light": "Sun",
        "description": "French tarragon creates a shrubby presence in the garden border, combining fine texture with wonderful green-to-gray foliage. Leaves dish up a sweet anise flavor used to create traditional Bearnaise sauce and the fines herbes blend vital to French cooking. In rich soil, plants practically jump out of the ground, thriving with little care. For best growth, remove flowering stems. With a sunny window and rich soil, you can raise French tarragon indoors. If light isn't strong enough, stems will likely sprawl and leaf flavor will diminish, but you'll still be able to savor the licorice taste. In the garden, pair French tarragon with bearded iris, burgundy-toned shrubs, or lilies for an eye-pleasing scene. In coldest zones, cut plants back in fall and mulch after the ground freezes.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2016%2F02%2F15232848%2F101061614.jpg&q=85",
        "propagation": "Division",
        "height": "1 to 3 feet",
        "width": "1-2 feet wide",
        "flower_color": "Green",
        "foliage_color": "Gray/Silver",
        "problem_solvers": "Deer Resistant",
        "special_features": "Good for Containers",
        "care_must_knows": "Artemisia dracunculus sativa is a popular herb that's very easy to grow. It reaches 2 feet tall and wide. Zones 5-9"
      },
      {
       
        "name": "Valerian",
        "genus": "Valeriana officinalis",
        "type": "Herb",
        "light": "Part Sun",
        "description": "This upright perennial herb, also called garden heliotrope, is topped with white to pinkish-white fragrant flowers in midsummer. The blooms were once used in perfume production. Cats also find the plant attractive and may rub against the foliage as they do with catnip. Valerian attracts butterflies to the garden. Remove spent flowers to prevent the plant from self-sowing.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2016%2F02%2F31224610%2F100875427.jpg&q=85",
        "propagation": "Division",
        "height": "3 to 8 feet",
        "width": "2-3 feet wide",
        "flower_color": "Pink",
        "foliage_color": "None",
        "problem_solvers": "None",
        "special_features": "Attracts Birds",
        "care_must_knows": "None"
      },
      {
        "name": "Vietnamese Coriander",
        "genus": "Persicaria odorata",
        "type": "Herb",
        "light": "Part Sun",
        "description": "This Southeast Asian native is often used as a coriander substitute in Vietnamese cuisine. It adds a lemony coriander flavor to fresh salads, summer rolls, soups, and salads. In Zones 10 and 11, it can be grown outdoors in a moist, semishaded location as a perennial. Elsewhere, grow it as an annual or in a container to bring indoors over winter. The silvery leaves often develop a maroon blotch that makes the plant quite ornamental.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2016%2F02%2F31224821%2F101620509.jpg&q=85",
        "propagation": "Division",
        "height": "1 to 3 feet",
        "width": "6-10 inches wide",
        "flower_color": "None",
        "foliage_color": "None",
        "problem_solvers": "None",
        "special_features": "None",
        "care_must_knows": "None"
      },
      {
       
        "name": "Epazote",
        "genus": "Dysphania ambrosioides",
        "type": "Herb",
        "light": "Part Sun",
        "description": "Epazote is a pungent tender perennial most commonly used in Mexican cooking. Use the leaves fresh or dried in bean dishes and soups. Epazote blends well with oregano, cumin, and chiles, but on its own it has a strong flavor that some compare to kerosene. Mature plants grow 2-3 feet tall. Epazote prefers a dry, sunny site, but isn't particular about growing conditions. In fact, it readily spreads throughout the garden unless you contain it and remove flower stalks before they set seed.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2016%2F02%2F31224706%2F101615577.jpg&q=85",
        "propagation": "Division",
        "height": "1 to 3 feet",
        "width": "To 3 feet wide",
        "flower_color": "None",
        "foliage_color": "None",
        "problem_solvers": "Drought Tolerant",
        "special_features": "Low Maintenance",
        "care_must_knows": "Mature plants grow 2-3 feet tall. Epazote prefers a dry, sunny site, but isn't particular about growing conditions. In fact, it readily spreads throughout the garden unless you contain it and remove flower stalks before they set seed."
      },
      {
        
        "name": "Cuban Oregano",
        "genus": "Plectranthus amboinicus",
        "type": "Herb",
        "light": "Part Sun",
        "description": "With common names that include Mexican mint, Spanish thyme, and Indian borage, Cuban oregano leaves many gardeners wondering exactly what it is when they encounter it at a garden center. Let’s start with what it is not. Cuban oregano isn’t actually oregano, or even mint, thyme, or borage. It is an herb that is perennial in tropical regions but most commonly grown as a container plant elsewhere. It has fragrant, velvety leaves edged in white, and trumpet-shape flowers in pink, white, and lavender. It grows rapidly, creating a lush display in a container garden.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2020%2F04%2F13%2Fcuban-oregano-b3ff8471.jpg&q=85",
        "propagation": "Stem Cuttings",
        "height": "1 to 3 feet",
        "width": "2 to 3 feet",
        "flower_color": "Purple",
        "foliage_color": "None",
        "problem_solvers": "Drought Tolerant",
        "special_features": "Low Maintenance",
        "care_must_knows": "Cuban oregano grows well in part-shade areas like porches, patios, or courtyards that receive a few hours of morning light. Plant this drought-tolerant plant in well-drained soil; water occasionally. It grows well in containers alongside other part-shade plants like begonia, impatiens, fuchsia, and coleus."
      },
      {
        
        "name": "Asparagus Fern",
        "genus": "Asparagus",
        "type": "Annual",
        "light": "None",
        "description": "Versatile asparagus fern is an attractive herbaceous perennial that is easy to grow, though not actually a fern. Plant asparagus fern in garden beds where it is used as a creeper in warmer climates. It can be invasive, so keep an eye on it. You will more often find asparagus fern growing indoors as a dense, bushy houseplant with lace-like foliage that forms an incredible mound.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2020%2F02%2Fsprengeri-asparagus-fern-28f13111.jpg&q=85",
        "propagation": "Division",
        "height": "1 to 3 feet",
        "width": "18 inches to 3 feet wide",
        "flower_color": "White",
        "foliage_color": "Blue/Green",
        "problem_solvers": "None",
        "special_features": "Low Maintenance",
        "care_must_knows": "Asparagus ferns perform best in an organically rich, well-drained soil. Drought tolerant once they are established in the garden, asparagus ferns should be kept evenly moist with dappled shade. As potted houseplants, asparagus ferns should be placed in indirect or filtered light for best results. During warmer months you can move asparagus ferns outdoors to a shaded porch. Asparagus ferns prefer warm and humid climates (about 70 degrees F) and cannot withstand temperatures below 55 degrees F for very long periods of time. Asparagus ferns do not require periods of winter dormancy but will appreciate a resting period and reduced watering during the winter months.\n\nTo promote dense plant growth, pinch back the stem tips. If plant shape becomes too sprawling, the stems can be cut back close to the soil to regenerate and encourage new growth. During their active growing period, apply a weak liquid fertilizer about once a week.\nYou'll know when asparagus fern needs to be divided or repotted. Watch for fleshy bulbs to push the plants out of the pot. At this point, you can repot in a slightly larger container or divide the plant. When dividing, be sure to take several of the underground bulbs. Mature asparagus fern plants can become quite woody with sharp spines on the branches. This is something to keep in mind when trimming older plants."
      },
      {
       
        "name": "Black Pepper",
        "genus": "Piper nigrum",
        "type": "Houseplant",
        "light": "Part Sun",
        "description": "Grow your own peppercorns with this lovely houseplant. A vine that produces chains of small round fruit, black pepper thrives in full or part sun and indoor temperatures above 65 degrees F. By selecting the time of harvest, all four types of peppercorns -- black, white, green, and red -- can be harvested from the same plant. Black pepper is a slow-growing vine, and plants take three to four years to start flowering and fruiting. Wait to water black pepper until the soil is visibly dry. When watering, thoroughly saturate the soil until a little water runs out the bottom of the pot.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2016%2F02%2F31223833%2F101736445.jpg&q=85",
        "propagation": "Division",
        "height": "8 to 20 feet",
        "width": "To 3 feet wide",
        "flower_color": "None",
        "foliage_color": "None",
        "problem_solvers": "None",
        "special_features": "Good for Containers",
        "care_must_knows": "None"
      },
      {
        
        "name": "New Zealand Spinach",
        "genus": "Tetragonia tetragonioides",
        "type": "Vegetable",
        "light": "Sun",
        "description": "Like Malabar spinach, New Zealand spinach is a great way to enjoy a tender green even in the heat of summer, when regular spinach doesn't grow well. In the warmest regions of the United States, it can be grown as a perennial, but in most regions it grows best as a warm-season annual.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2016%2F02%2F31224735%2F101025501.jpg&q=85",
        "propagation": "Seed",
        "height": "1 to 3 feet",
        "width": "1-3 feet wide",
        "flower_color": "None",
        "foliage_color": "None",
        "problem_solvers": "None",
        "special_features": "None",
        "care_must_knows": "Plant New Zealand spinach in full sun. New Zealand spinach prefers moisture-retentive, well-drained soil rich in organic matter. New Zealand spinach is weak-stemmed and will appear to trail across the garden. Set plants in hills similar to squash. New Zealand spinach prefers a soil pH of 6.8 to 7.0. Prepare planting beds with well-aged compost. Where summer heat is intense, plant New Zealand spinach where it will get partial shade in the afternoon. Sow New Zealand spinach ½ inch (12mm) deep and 2 to 4 inches (5-10cm) apart. New Zealand spinach grows from seed clusters that produce several seedlings, similar to beet seed. Soak seeds overnight in water to speed germination. When seedlings are 3 inches (7cm) tall, thin to the strongest seedlings, from 12 to 18 inches (30-45cm) apart. Set New Zealand spinach in hills similar to squash. This will allow the weak-stem to sprawl. Space hills or rows 24 to 36 inches (61-91cm) apart."
      },
      {
        
        "name": "Okra",
        "genus": "Abelmoschus esculentus",
        "type": "Vegetable",
        "light": "Sun",
        "description": "Traditionally a favorite in the South, okra is growing more popular in home gardens everywhere. It’s easy to learn why. Okra is a nutritious vegetable that’s easy to grow and ornamental—what’s not to love?",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2015%2F06%2F16003317%2F101074395.jpg&q=85",
        "propagation": "Seed",
        "height": "3 to 8 feet",
        "width": "3 to 4 feet wide",
        "flower_color": "Yellow",
        "foliage_color": "Blue/Green",
        "problem_solvers": "None",
        "special_features": "Good for Containers",
        "care_must_knows": "Okra is an annual vegetable that loves summer heat. Whether you grow it from seed or buy transplants, you'll find it does best if you wait to plant it outdoors until night temperatures reliably stay above 55°F."
      },
      {
    
        "name": "Onion",
        "genus": "Allium cepa",
        "type": "Vegetable",
        "light": "Sun",
        "description": "The onion is an easy-to-grow vegetable that’s big on flavor. Whether you grow sweet onions or storage onions, fresh onions are delicious on salads, sautéed, or caramelized in a variety of savory dishes. Plant a diverse crop of onions, including a variety or two that stores well, and enjoy garden-fresh onions year-round. Full sun and moist, well-drained soil are all you need for a prolific onion crop.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2019%2F01%2F15220349%2FMWL408500.jpg&q=85",
        "propagation": "Seed",
        "height": "6 to 12 inches",
        "width": "1-5 inches wide",
        "flower_color": "None",
        "foliage_color": "None",
        "problem_solvers": "None",
        "special_features": "None",
        "care_must_knows": "Allium cepa 'Copra Hybrid' is a widely adapted long-day yellow storage onion that is sweeter than most other storage onions. Onions can be started from seed or from sets (tiny bulbets). With seeds you have more choice of varieties, and you can choose varieties that are suited to your region. (In the North, plant long-season onions in the spring; in the South, short season onions, planted in the fall, are best.)\nStart your seeds, transplant into larger cells, and before planting out, harden them off by putting the pots outside for several days. In the garden, onion plants should be spaced 4 to 6 inches apart in the row, with rows 1 to 2 feet apart. Plant each one about 1/2 inch deep in a small hole. After planting, trim the tops to about 4 inches.\nOnions need about 1 inch of water per week, so if the weather is dry, you’ll need to water."
      },
      {
         "name": "Parsnip",
        "genus": "Pastinaca sativa",
        "type": "Vegetable",
        "light": "Sun",
        "description": "Parsnip is a vegetable that might not sound exciting, but it's absolutely delicious in soups and stews, where it adds a sweet note. Parsnips are also great boiled and mashed up with potatoes, adding sweetness and depth to that classic dish.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2016%2F02%2F31224822%2F101127009.jpg&q=85",
        "propagation": "Seed",
        "height": "6 to 12 inches",
        "width": "6-12 inches wide",
        "flower_color": "None",
        "foliage_color": "None",
        "problem_solvers": "None",
        "special_features": "None",
        "care_must_knows": "Pastinaca sativa 'Andover' is a productive variety with long, cylindrical roots and a rounded crown. It has good resistance to canker. Expose plants to 2-4 weeks of low temperatures before harvest to build up the sugar content of the roots. In warm areas, you can harvest roots all winter. In colder regions, you can mulch the bed with several inches of straw and harvest in early spring before plants start to grow again"
      },
      {
        
        "name": "Pea",
        "genus": "Pisum sativum",
        "type": "Vegetable",
        "light": "Sun",
        "description": "Peas are a spring garden staple, loved for their easy-to-grow nature, delicious seeds, and nutritional value. There’s something magical about harvesting peas fresh from the garden and tasting their sweet, fresh flavor.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2016%2F02%2F31230214%2F100331359.jpg&q=85",
        "propagation": "Seed",
        "height": "1 to 3 feet",
        "width": "6-12 inches wide",
        "flower_color": "White",
        "foliage_color": "Blue/Green",
        "problem_solvers": "None",
        "special_features": "Good for Containers",
        "care_must_knows": "Like most vegetables, peas do best in a spot with full sun (at least 6 to 8 hours of direct light per day). Water peas regularly to keep the soil moist but not wet and soggy. If your yard has clay soil, amending liberally with organic matter can help produce better harvests and reduce the chance of seeing root rot in periods of wet weather. You can also grow peas in containers or raised beds to offer the conditions they need to thrive. Growing them in containers or raised beds makes them easier to harvest, too, as you don't need to bend down as far to pluck the pods from the plants."
      },
      {
        "name": "Peanuts",
        "genus": "Arachis hypogaea",
        "type": "Vegetable",
        "light": "Sun",
        "description": "Growing and harvesting peanuts is a little like hosting your own treasure hunt. These warm season plants are easy to grow in areas with long, hot summers and moist, well-drained soil. When the peanut foliage turns yellow, it’s time to go on a dig for your treasure. The underground nuts are ready to eat a few weeks after digging and drying. Grow peanuts in the vegetable garden where the soil is loose and moist.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2016%2F02%2F31225512%2F101126992.jpg&q=85",
        "propagation": "Seed",
        "height": "1 to 3 feet",
        "width": "1-3 feet wide",
        "flower_color": "None",
        "foliage_color": "None",
        "problem_solvers": "None",
        "special_features": "None",
        "care_must_knows": "Peanuts grow best in full sun and well-drained soil. This root crop languishes in clay and poorly drained soil. Plant peanuts after the danger of frost has passed and soil is at least 65°F. Sow seeds 1 to 1½ inches deep and 6 to 8 inches apart. Row spacing for bunch types should be about 24 inches apart, and 36 inches apart for runner types.\n\nPeanut plants bloom about 30 to 40 days after germination. After pollination, peanuts develop in 9 to 10 weeks. Peanut plants flower over a period of several weeks, meaning all the pods do not mature at the same time. Promote a strong peanut crop by cultivating around plants to remove weeds. Work carefully and shallowly, being careful not to damage peanut roots.\nHarvest peanuts when the foliage begins to turn yellow. Use a spading fork to gently lift the peanut plants out of the ground. Shake off loose soil. Cure or dry plants by hanging them in a warm, dry, shaded place, such as a shed or garage, for about two weeks. After 2 weeks shake off any remaining soil and pull peanuts pods from the plants. Continue to air-dry the peanuts for an additional 1 to 2 weeks."
      },
      {
        "name": "Pumpkin",
        "genus": "Cucurbita maxima",
        "type": "Vegetable",
        "light": "Sun",
        "description": "From giant pumpkins that weigh hundreds of pounds to miniature pumpkins that fit neatly in the palm of your hand, there’s a pumpkin for every gardener. Growing pumpkins is easy, though it can require ample space. There’s a reason they call it a pumpkin patch: These autumn treasures need room and grow several feet out in all directions. Traditional orange jack-o’-lantern pumpkins are a top choice for carving, but it’s also fun to try other colors: white, buff, blue-green, and scarlet.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2020%2F04%2F29%2Fvariety-orange-yellow-white-pumpkins-eb4d1c60.jpg&q=85",
        "propagation": "Seed",
        "height": "1 to 3 feet",
        "width": "3 to 15 feet wide",
        "flower_color": "Yellow",
        "foliage_color": "Blue/Green",
        "problem_solvers": "None",
        "special_features": "Low Maintenance",
        "care_must_knows": "If you want good harvests, be sure to plant pumpkins in full sun (at least 6 to 8 hours of direct sun per day) with well-draining soil. If your ground has a high sand or clay content, amend it liberally with organic matter such as compost, peat, or coir to fuel your pumpkin plants' rampant growth. This is especially important if you're growing giant varieties.\n\nBecause pumpkins are heat-loving plants, place seeds or transplants outdoors after soil temperatures remain above 60 degrees F. If you put them out too early and it's still cold, your seeds or young plants will sulk in cool weather and potentially rot before they grow. If you're in a short-summer area, start your pumpkin seeds indoors three to four weeks before you'd normally plant them outdoors to get a head start on the season.\nIf you grow pumpkins in rows, space your plantings 3-6 feet apart. Protect pumpkins from pests like squash vine borers by using floating row covers in spring until the plants grow too large for them.\nLeave pumpkins on the vine until the skin turns the appropriate color for the variety and the rind feels hard when pressed with your thumbnail. Harvest before a hard frost by cutting the stem from the vine with a sharp knife, leaving a 2-inch stub on the fruit. Place the harvested pumpkins at 80° to 85°F for two weeks to cure them. For longer term storage, place them in a dark location at 50° to 55°F."
      },
      {
        "name": "Water Lettuce",
        "genus": "Pistia stratiodes",
        "type": "Water Plant",
        "light": "Part Sun",
        "description": "This water plant is grown for its beautiful, velvety foliage that really does resemble a dense carpet of lettuce heads flowering on the water. It can be an important plant for ponds as it shades the water and gives small fish a place to hide. In cold climates, treat this tender floating plant as an annual and replace every year.",
        "image": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2016%2F02%2F31214632%2F100861981.jpg&q=85",
        "propagation": "Division",
        "height": "Under 6 inches",
        "width": "Can spread indefinitely",
        "flower_color": "None",
        "foliage_color": "None",
        "problem_solvers": "None",
        "special_features": "Low Maintenance",
        "care_must_knows": "Water lettuce grows floating on the surface water, and its leaves form a rosette, with dense, submerged roots beneath it. These plants grow like a weed outdoors, but they can be very challenging to grow in the home aquarium. However, if they are provided with the right conditions, they can completely overrun an aquarium, and in most cases, it’s a good idea to remove a few plants during weekly tank maintenance."
      },

]